name       : feedreader
version    : 1.6.2
release    : 13
source     :
    - https://github.com/jangernert/FeedReader/archive/v1.6.2.tar.gz : c9ddb59d14a2cb04d00db07fcd90f3de07f9ae1f2fb0f21783db8e9a242991ed
license    : GPL-3.0
summary    : FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
component  : desktop
description: |
    FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-0.7)
    - pkgconfig(libnotify)
    - vala
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF ..
build      : |
    cd build
    %make -j1
install    : |
    cd build
    %make_install
