name       : feedreader
version    : 2.0
release    : 15
source     :
    - https://github.com/jangernert/FeedReader/archive/v2.0.tar.gz : eba631c2c1a644d815accb2234e72d161a9f45383c19d57c4fdda9ff1ee75135
license    : GPL-3.0
summary    : FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS
    or Feeldy.
component  : desktop
description: |
    FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(goa-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF ..
build      : |
    cd build
    %make -j1
install    : |
    cd build
    %make_install
