name       : feedreader
version    : 1.2
release    : 2
source     :
    - https://launchpad.net/feedreader/1.2/1.2-final/+download/FeedReader_1_2.tar.gz : 6957c0710959c604c6678389b50968b0dcf3c39fda659889c8e6a611336f84a1
license    : GPL-3.0
summary    : FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
description: |
    FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-0.7)
    - pkgconfig(libnotify)
    - vala
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
