name       : feedreader
version    : 1.4.1
release    : 6
source     :
    - https://launchpad.net/feedreader/1.4/1.4.1/+download/FeedReader-1.4.1.tar.gz : 1a0fcaf3d6bbd6bc75e3ef85e2d00e63ad85b150c566212de3b8f58decd0cfeb
license    : GPL-3.0
summary    : FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
description: |
    FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-0.7)
    - pkgconfig(libnotify)
    - vala
rundeps    :
    - vilistextum
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF ..
build      : |
    cd build
    %make -j1
install    : |
    cd build
    %make_install
