name       : feedreader
version    : 2.0.2
release    : 18
source     :
    - https://github.com/jangernert/FeedReader/archive/v2.0.2.tar.gz : 949262912bc07f8d1ec72dfa1bbeafb0ed1cea992589e1ee5901e0630c714261
license    : GPL-3.0
summary    : FeedReader is a client for popular RSS-Web-Services.
component  : desktop
description: |
    FeedReader is a client for popular RSS-Web-Services which supports:
    - TinyTinyRSS
    - Feeldy
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(goa-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - vala
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF ..
build      : |
    cd build
    %make -j1
install    : |
    cd build
    %make_install
