name       : feedreader
version    : 1.4.2
release    : 7
source     :
    - https://launchpad.net/feedreader/1.4/1.4.2/+download/FeedReader-1.4.2.tar.gz : 5c866ccdbb5e642bf1e6a91370393fc44a688ee4da4f2bd4a693bf3491ada275
license    : GPL-3.0
summary    : FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
description: |
    FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-0.7)
    - pkgconfig(libnotify)
    - vala
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF ..
build      : |
    cd build
    %make -j1
install    : |
    cd build
    %make_install
