name       : feedreader
version    : 2.8.2
release    : 31
source     :
    - https://github.com/jangernert/FeedReader/archive/v2.8.2.tar.gz : 40ec53a5bdb745909b486092fb0c91686b2f1a76fce5416514f62c3f3617f612
license    : GPL-3.0-or-later
summary    : Modern desktop application designed to complement existing web-based
    RSS accounts
component  : network.news
description: |
    FeedReader is a modern desktop application designed to complement existing web-based RSS accounts. It combines all the advantages of web based services like synchronisation across all your devices with everything you expect from a modern desktop application.
libsplit   : no
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(goa-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gumbo)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libnotify)
    - pkgconfig(libpeas-1.0)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-0.7)
    - pkgconfig(sqlite3)
    - pkgconfig(webkit2gtk-4.0)
    - vala
rundeps    :
    - gnome-keyring
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
