name       : feedreader
version    : 1.4.3
release    : 9
source     :
    - https://launchpad.net/feedreader/1.4/1.4.3/+download/FeedReader-1.4.3.tar.gz : e43ceb9eb866c2e8e16d460b6914e6450b2c97fe62f0730a2ec67a3c7d7f0a3c
license    : GPL-3.0
summary    : FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
description: |
    FeedReader is a client for popular RSS-Web-Services such as TinyTinyRSS or Feeldy.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(json-glib-1.0)
    - pkgconfig(gee-0.8)
    - pkgconfig(libsoup-2.4)
    - pkgconfig(webkit2gtk-3.0)
    - pkgconfig(sqlite3)
    - pkgconfig(libsecret-1)
    - pkgconfig(rest-0.7)
    - pkgconfig(libnotify)
    - vala
setup      : |
    mkdir build
    cd build
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DWITH_LIBUNITY=OFF ..
build      : |
    cd build
    %make -j1
install    : |
    cd build
    %make_install
